// ===== TYPESCRIPT PROJECT SETUP & COMPILATION =====
// Understanding how TypeScript works in real projects

console.log("=== TypeScript Compilation Process ===");
/*
TypeScript is a SUPERSET of JavaScript that adds static typing.
It needs to be COMPILED (transpiled) to JavaScript to run in browsers/Node.js.

FLOW: .ts files → TypeScript Compiler (tsc) → .js files → Browser/Node.js

Example:
- You write: function greet(name: string): string { return Hello ${name}; }
- Compiler outputs: function greet(name) { return "Hello " + name; }
*/

console.log("=== Project Structure ===");
/*
my-project/
├── src/                    ← SOURCE directory (your TypeScript code)
│   ├── index.ts           ← Main TypeScript entry point
│   ├── utils/
│   │   └── helpers.ts
│   └── components/
│       └── Button.ts
├── dist/                   ← DISTRIBUTION directory (compiled JavaScript)
│   ├── index.js           ← Compiled from src/index.ts
│   ├── utils/
│   │   └── helpers.js
│   └── components/
│       └── Button.js
├── public/                 ← Static files (HTML, CSS, images)
│   └── index.html         ← HTML file that loads the compiled JS
├── tsconfig.json          ← TypeScript configuration
├── package.json           ← Project metadata & dependencies
├── package-lock.json      ← Exact dependency versions (auto-generated)
└── node_modules/          ← Installed dependencies (don't commit this!)
*/

// ===== DIRECTORY EXPLANATIONS =====

console.log("=== SRC Directory ===");
/*
src/ - Where you write your TypeScript code
- Contains ALL your .ts files
- This is your "development" code
- Has type annotations, interfaces, etc.
- NOT what runs in the browser
- Example: src/index.ts, src/components/Button.ts
*/

console.log("=== DIST Directory ===");
/*
dist/ - Where compiled JavaScript goes
- Generated automatically by TypeScript compiler
- Contains .js files (no types)
- This is what actually runs in browser/Node.js
- Should be in .gitignore (don't commit compiled files)
- Example: dist/index.js, dist/components/Button.js
*/

// ===== FILE EXPLANATIONS =====

console.log("=== File Types ===");

// index.ts vs index.js
const exampleTS = `
index.ts (TypeScript source):
- Has type annotations
- Written by YOU
- Example: function add(a: number, b: number): number { return a + b; }

index.js (JavaScript output):
- Generated by TypeScript compiler
- NO type annotations
- Example: function add(a, b) { return a + b; }
`;

// index.html
const htmlExample = `
index.html:
- Entry point for web applications
- Links to compiled JavaScript (NOT TypeScript)
- Contains script tag pointing to dist/index.js
- NOT to src/index.ts (TypeScript source)
`;

// package.json vs package-lock.json
const packageExample = `
package.json:
- Project configuration file
- Lists dependencies with version RANGES
- Written/modified by YOU
- Example: "typescript": "^5.0.0" (allows 5.0.0 to 5.x.x)

package-lock.json:
- Auto-generated by npm
- Lists EXACT versions of ALL dependencies
- Ensures everyone installs same versions
- Should be committed to git
- DON'T edit manually
- Example: "typescript": "5.3.2" (exact version)
`;

console.log(exampleTS);
console.log(htmlExample);
console.log(packageExample);

// ===== TSCONFIG.JSON EXPLAINED =====
console.log("=== tsconfig.json Configuration ===");

interface TSConfig {
    compilerOptions: {
        target: string;        // What JS version to compile to
        module: string;        // Module system (commonjs, es6, etc.)
        outDir: string;        // Where to put compiled JS files
        rootDir: string;       // Where TypeScript source files are
        strict: boolean;       // Enable all strict type checking
        esModuleInterop: boolean;     // Better import/export compatibility
        skipLibCheck: boolean;        // Skip type checking of .d.ts files
        forceConsistentCasingInFileNames: boolean;
    };
    include: string[];         // Which files to compile
    exclude: string[];         // Which files to ignore
}

const exampleTSConfig: TSConfig = {
    compilerOptions: {
        target: "ES2020",
        module: "commonjs",
        outDir: "./dist",          // 📁 Where compiled JS goes
        rootDir: "./src",          // 📁 Where TS source files are
        strict: true,              // Enable strict type checking
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true
    },
    include: ["src/**/*"],         // Which files to compile
    exclude: ["node_modules", "dist"]   // Which files to ignore
};

console.log("Example tsconfig.json:", JSON.stringify(exampleTSConfig, null, 2));

// ===== COMPILATION COMMANDS =====
console.log("=== TypeScript Compilation Commands ===");

const commands = {
    compileOnce: "npx tsc",
    compileWithConfig: "npx tsc --project tsconfig.json",
    compileSpecificFile: "npx tsc src/index.ts",
    watchMode: "npx tsc --watch",
    watchModeShort: "npx tsc -w"
};

console.log("Available commands:");
Object.entries(commands).forEach(([name, command]) => {
    console.log(`${name}: ${command}`);
});

console.log("Watch mode is ESSENTIAL for development!");

// ===== WATCH MODE EXPLAINED =====
console.log("=== Watch Mode ===");
/*
Watch Mode (tsc --watch):
- Monitors your .ts files for changes
- Automatically recompiles when you save
- Keeps running until you stop it (Ctrl+C)
- Shows compilation errors in real-time

Example workflow:
1. Terminal 1: npx tsc --watch    ← Keeps TypeScript compiler running
2. Terminal 2: lite-server        ← Serves your files
3. Edit .ts files → Auto-compiles → Browser auto-refreshes
*/

// ===== LITE-SERVER CONCEPT =====
console.log("=== lite-server Development Server ===");
/*
lite-server:
- Lightweight development web server
- Serves static files (HTML, CSS, JS)
- Auto-refreshes browser when files change
- Perfect for frontend development

Installation:
npm install lite-server --save-dev

Usage:
npx lite-server

What it does:
1. Serves files from current directory
2. Opens browser automatically
3. Watches for file changes
4. Refreshes browser when JS/HTML changes

Perfect combo with tsc --watch:
- Terminal 1: npx tsc --watch     ← Compiles TS → JS
- Terminal 2: npx lite-server     ← Serves files + auto-refresh
*/

// ===== DEVELOPMENT WORKFLOW =====
console.log("=== Development Workflow ===");

const workflowSteps = [
    "mkdir my-typescript-project",
    "cd my-typescript-project",
    "npm init -y",
    "npm install typescript --save-dev",
    "npm install lite-server --save-dev",
    "mkdir src dist public",
    "Create tsconfig.json with proper configuration",
    "Write TypeScript code in src/index.ts",
    "Create HTML file in public/index.html",
    "Start development: npx tsc --watch (Terminal 1)",
    "Start server: npx lite-server (Terminal 2)",
    "Edit .ts files → Auto-compiles → Browser refreshes"
];

workflowSteps.forEach((step, index) => {
    console.log(`${index + 1}. ${step}`);
});

// ===== PACKAGE.JSON SCRIPTS =====
console.log("=== Useful Package.json Scripts ===");

interface PackageScripts {
    build: string;
    dev: string;
    serve: string;
    start: string;
}

const scripts: PackageScripts = {
    build: "tsc",                    // Compile once
    dev: "tsc --watch",              // Watch mode
    serve: "lite-server",            // Start server
    start: "npm run build && npm run serve"  // Build & serve
};

console.log("Add these to package.json scripts section:");
console.log(JSON.stringify(scripts, null, 2));

console.log("Then use: npm run build, npm run dev, npm run serve, npm start");

// ===== COMMON TSCONFIG OPTIONS =====
console.log("=== Common tsconfig.json Options ===");

interface CompilerOptions {
    // Output settings
    outDir: string;
    rootDir: string;
    target: string;
    module: string;
    
    // Type checking
    strict: boolean;
    noImplicitAny: boolean;
    strictNullChecks: boolean;
    noUnusedLocals: boolean;
    noUnusedParameters: boolean;
    
    // Module resolution
    esModuleInterop: boolean;
    allowSyntheticDefaultImports: boolean;
    moduleResolution: string;
    
    // Development
    sourceMap: boolean;
    removeComments: boolean;
    declaration: boolean;
    
    // Compatibility
    skipLibCheck: boolean;
    forceConsistentCasingInFileNames: boolean;
}

const commonOptions: CompilerOptions = {
    // Output settings
    outDir: "./dist",              // 📁 Output directory
    rootDir: "./src",              // 📁 Source directory
    target: "ES2020",              // JS version to compile to
    module: "commonjs",            // Module system
    
    // Type checking
    strict: true,                  // Enable all strict checks
    noImplicitAny: true,          // Error on implicit 'any'
    strictNullChecks: true,        // Strict null/undefined checks
    noUnusedLocals: true,         // Error on unused variables
    noUnusedParameters: true,      // Error on unused parameters
    
    // Module resolution
    esModuleInterop: true,         // Better import compatibility
    allowSyntheticDefaultImports: true,
    moduleResolution: "node",      // How to resolve modules
    
    // Development
    sourceMap: true,               // Generate .map files for debugging
    removeComments: true,          // Remove comments from output
    declaration: true,             // Generate .d.ts files
    
    // Compatibility
    skipLibCheck: true,            // Skip type checking .d.ts files
    forceConsistentCasingInFileNames: true
};

// ===== REAL WORLD EXAMPLE =====
console.log("=== Real World Example ===");

// Example TypeScript code that would be in src/math.ts
interface Calculator {
    add(a: number, b: number): number;
    subtract(a: number, b: number): number;
}

class SimpleCalculator implements Calculator {
    add(a: number, b: number): number {
        return a + b;
    }
    
    subtract(a: number, b: number): number {
        return a - b;
    }
}

// Example TypeScript code that would be in src/index.ts
const calc = new SimpleCalculator();
console.log(`5 + 3 = ${calc.add(5, 3)}`);
console.log(`10 - 4 = ${calc.subtract(10, 4)}`);

console.log("After compilation (npx tsc), TypeScript generates JavaScript:");
console.log("- Types are removed");
console.log("- Modern JS features are converted to target version");
console.log("- Files are placed in dist/ directory");

// ===== TROUBLESHOOTING =====
console.log("=== Common Issues & Solutions ===");

const troubleshootingGuide = {
    "Cannot find module errors": [
        "Check your import paths",
        "Make sure files are in src/ directory",
        "Check tsconfig.json include/exclude"
    ],
    "Property does not exist errors": [
        "Check your type definitions",
        "Make sure you're importing correctly",
        "Check for typos in property names"
    ],
    "Compilation errors": [
        "Run: npx tsc --noEmit (check without compiling)",
        "Check tsconfig.json syntax",
        "Make sure all dependencies are installed"
    ],
    "Browser shows old code": [
        "Clear browser cache",
        "Check if dist/ files are updated",
        "Make sure HTML links to correct JS files"
    ],
    "lite-server not working": [
        "Make sure it's installed: npm install lite-server --save-dev",
        "Check if port is available",
        "Try running from correct directory"
    ]
};

Object.entries(troubleshootingGuide).forEach(([problem, solutions]) => {
    console.log(`\n${problem}:`);
    solutions.forEach(solution => console.log(`  - ${solution}`));
});

// ===== SUMMARY =====
console.log("\n=== TypeScript Project Setup Summary ===");
console.log("📁 src/        - Your TypeScript source code");
console.log("📁 dist/       - Compiled JavaScript output");
console.log("📁 public/     - Static files (HTML, CSS)");
console.log("📄 tsconfig.json - TypeScript configuration");
console.log("📄 package.json - Project configuration & dependencies");
console.log("📄 package-lock.json - Exact dependency versions");
console.log("");
console.log("🔧 Commands:");
console.log("   npx tsc        - Compile once");
console.log("   npx tsc --watch - Watch mode (auto-compile)");
console.log("   npx lite-server - Development server");
console.log("");
console.log("🚀 Workflow:");
console.log("   1. Write TypeScript in src/");
console.log("   2. Compiler generates JavaScript in dist/");
console.log("   3. HTML loads JavaScript from dist/");
console.log("   4. Browser runs the JavaScript");
console.log("");
console.log("🎯 Key Concepts:");
console.log("   • TypeScript compiles to JavaScript");
console.log("   • src/ = your code, dist/ = compiled output");
console.log("   • tsconfig.json controls compilation");
console.log("   • Watch mode auto-compiles on changes");
console.log("   • lite-server provides development server");

export {}; 